version: "3"

services:
  mysql:
    container_name: cozinha_na_cozinha_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=${DESOFS_DB_DEV_DB_NAME}
      - MYSQL_USER=${DESOFS_DB_USER}
      - MYSQL_PASSWORD=${DESOFS_DB_PASS}

    # adminer:
    #   image: adminer
    #   depends_on:
    #     - mysql
    #   ports:
    #     - 8080:8080
  phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      ports:
        - 8090:80
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: rootpwd 
networks:
  cozinha_na_cozinha:
    name: cozinha_na_cozinha
    driver: bridge