version: "3"

services:
  mysql:
    container_name: cozinha_na_cozinha_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DESOFS_DB_DEV_DB_NAME}
      - MYSQL_USER=${DESOFS_DB_USER}
      - MYSQL_PASSWORD=${DESOFS_DB_PASS}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpwd


networks:
  cozinha_na_cozinha:
    driver: bridge
